# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :build_debug do
    gradle(
      task: "clean assembleDebug",
      project_dir: "android/",
    )
  end
end

platform :ios do
  lane :build_simulator do
    build_ios_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      sdk: "iphonesimulator",
      skip_package_ipa: true,
      skip_archive: true,
      export_method: "development",
      destination: "generic/platform=iOS Simulator",
      derived_data_path: "./output",
      xcargs: "-verbose",
    )
  end
end