name: Build Android debug APK

on:
  push:
    branches:
    - main
    - add-fastlane

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Confirm fastlane install
      run: fastlane -v